[app]
name = "polaris-shopify-app"
client_id = "process.env.SHOPIFY_API_KEY"
application_url = "https://polaris-developers.vercel.app"
embedded = true

[webhooks]
api_version = "2024-01"

[access_scopes]
scopes = "write_payment_gateways,read_payment_gateways,write_checkouts,read_checkouts"

[auth]
redirect_urls = [
  "https://polaris-developers.vercel.app/auth/callback",
  "https://polaris-developers.vercel.app/auth/shopify/callback",
  "https://polaris-developers.vercel.app/api/auth/callback"
]

[pos]
embedded = false
